# Generated by Gemini 3.1 Pro
# 1. Verify Java (Temurin) is installed
describe package('temurin-21-jdk') do
  it { should be_installed }
end

# 2. Verify Jenkins is installed, enabled, and running
describe package('jenkins') do
  it { should be_installed }
end

describe service('jenkins') do
  it { should be_installed }
  it { should be_enabled }
  it { should be_running }
end

# 3. Verify Jenkins is listening on its default web port
describe port(8080) do
  it { should be_listening }
end

# 4. Verify the Plugin Manager jar exists with correct permissions
describe file('/usr/local/jenkins/jars/jenkins-plugin-manager.jar') do
  it { should exist }
  its('owner') { should eq 'jenkins' }
  its('group') { should eq 'jenkins' }
  its('mode') { should cmp '0644' }
end

# 5. Verify the Jenkins CLI jar was downloaded successfully
describe file('/usr/local/jenkins/jars/jenkins-cli.jar') do
  it { should exist }
end
