---
name: CI

on:
  pull_request:
  push:
    branch: ["latest"]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: yamllint
        uses: actionshub/yamllint@00f4f7f756a93a38e77ea1af41a46b48fd893dcd  # v1.8.3

  kitchen:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform:
          - ubuntu-2404
        chef_version:
          - "17"
          - "18"
        suite:
          - "jenkins-default"
          - "jenkins-custom-java-opts"
    steps:
      - name: Check out sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Install Cinc
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh -o /tmp/install-cinc.sh
          # This is only the chef version used for installing chef workstation in the CI environment.
          # The chef version used in each configuration is configured in kitchen.dokken.yml.
          sudo sh /tmp/install-cinc.sh -c stable -P cinc-workstation -v 18
      - name: "Test Kitchen Converge"
        env:
          CHEF_VERSION: ${{ matrix.chef_version }}
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        run: |
          kitchen converge ${{ matrix.suite }}-${{ matrix.platform }}
